
name: gitl
base: core18
version: '2.0.1'
summary: Git loop
description: Git loop inspired by gitsh.

grade: stable
confinement: strict

parts:
  gitl:
    plugin: dump
    source: https://github.com/wieczorek1990/gitl.git
    source-type: git
    stage-packages:
      - git
      - python3

plugs:
  gitconfig:
    interface: personal-files
    write:
      - $HOME/.gitconfig
      - $HOME/.config/git/config

apps:
  gitl:
    command: bin/gitl.py
    plugs:
      - home
      - removable-media
      - gitconfig