
name: gitl
base: core18
version: '2.0.2'
summary: Git loop
description: Git loop inspired by gitsh.

grade: stable
confinement: strict

parts:
  gitl:
    plugin: dump
    source: .
    stage-packages:
      - git
      - openssh-client
      - python3

plugs:
  gitl:
    interface: personal-files
    write:
      - $HOME/.gitconfig
      - $HOME/.gitl_history
      - $HOME/.config/git/config

apps:
  gitl:
    command: bin/gitl.py
    plugs:
      - home
      - removable-media
      - gitl
