
name: gitl
base: core20
version: git
summary: Git loop
description: Git loop inspired by gitsh.

grade: stable
confinement: strict

parts:
  gitl:
    plugin: dump
    source: .
    stage-packages:
      - git
      - openssh-client
      - python3
  gitl-python:
    plugin: python
    source: .
    stage-packages:
      - libncurses-dev
    requirements:
      - requirements.txt

plugs:
  gitconfig:
    interface: personal-files
    write:
      - $HOME/.gitconfig
      - $HOME/.config/git/config

apps:
  gitl:
    command: bin/gitl.py
    plugs:
      - home
      - removable-media
      - gitconfig
